### ISSUE TITLE
Nodes and Properties duplicate and disappear

### ISSUE THREAD

**Issue by DominicWuest** [FalkorDB/falkordb-go#5]
I was using this driver and stumbled upon some issues where properties disappear and labels duplicate when running queries.
This same problem doesn't occur when using `redis-cli` or the Python client.

I wrote about this problem in two issues on FalkorDB:
https://github.com/FalkorDB/FalkorDB/issues/628
https://github.com/FalkorDB/FalkorDB/issues/630

This issue arises in the oldest published version of `redisgraph-go`, the latest commit in `redisgraph-go` and the latest commit in this repo.

**Comment by swilly22** [comment]
@AviAvni could you please take a look ?

**Comment by AviAvni** [comment]
just checked both queries and they return the correct result

**Comment by DominicWuest** [comment]
Could you try running the following Go code and see what it outputs?

```go
package main

import (
	"context"

	"github.com/FalkorDB/falkordb-go"
)

func Main() {
	fdbConn, _ := falkordb.FalkorDBNew(&falkordb.ConnectionOption{
		Addr:     "localhost:6379",
		Protocol: 3,
	})
	graph := fdbConn.SelectGraph("")

	fdbConn.Conn.FlushAll(context.Background())

	returned, _ := graph.Query("CREATE (y{N:0, M:0}) RETURN y", nil, nil)
	returned.PrettyPrint()

	fdbConn.Conn.FlushAll(context.Background())

	returned1, _ := graph.Query("CREATE (x{n0:0}) DELETE x CREATE (y{N:0, M:0}) RETURN y", nil, nil)
	returned1.PrettyPrint()
}
```

For me, I get:
```
+-----------+
|     y     |
+-----------+
| {N:0,M:0} |
+-----------+

Nodes created 1.000000
Properties set 2.000000
Cached execution 0.000000
Query internal execution time 1.081698


+-------+
|   y   |
+-------+
| {M:0} |
+-------+

Query internal execution time 1.051177
Nodes created 2.000000
Properties set 3.000000
Nodes deleted 1.000000
Cached execution 0.000000
```

Am I using the driver in an unintended way?

**Comment by AviAvni** [comment]
the problem is how you use the client
the client maintain a cached schema
when you call FlushAll you make discrepancy between the schema cached in the client and the schema in the database
when ever you flush the db just call SelectGraph again to get rid of the old cached schema

**Comment by swilly22** [comment]
@DominicWuest I can see how this can cause confusion. on other clients e.g. our Python client we've got a `graph.delete` API which replaces `FlushAll` we'll add this functionality to our Go client shortly.

**Comment by DominicWuest** [comment]
Works like a charm, thanks for the help @swilly22 and @AviAvni!
